package app.muxtv.database

import com.google.common.truth.Truth.assertThat
import org.junit.Test

class SearchDocumentWritePlanTest {
    @Test
    fun existingDocumentBecomesRowidPreservingUpdate() {
        val existing = document(rowId = 41, key = "overlay-name:p:c", text = "Старое")
        val desired = document(rowId = 0, key = existing.documentKey, text = "Новое")

        val plan = planSearchDocumentWrites(listOf(desired), listOf(existing))

        assertThat(plan.inserts).isEmpty()
        assertThat(plan.updates).containsExactly(desired.copy(rowId = 41))
    }

    @Test
    fun unchangedExistingDocumentProducesNoWrite() {
        val existing = document(rowId = 41, key = "overlay-name:p:c", text = "То же")
        val desired = existing.copy(rowId = 0)

        val plan = planSearchDocumentWrites(listOf(desired), listOf(existing))

        assertThat(plan.inserts).isEmpty()
        assertThat(plan.updates).isEmpty()
    }

    @Test
    fun missingDocumentRemainsAutogeneratedInsert() {
        val desired = document(rowId = 0, key = "canonical-name:c", text = "Россия 1")

        val plan = planSearchDocumentWrites(listOf(desired), emptyList())

        assertThat(plan.inserts).containsExactly(desired)
        assertThat(plan.updates).isEmpty()
    }

    @Test
    fun duplicateDesiredKeysAreRejectedBeforeDatabaseWrite() {
        val duplicate = document(rowId = 0, key = "same", text = "One")

        val error = runCatching {
            planSearchDocumentWrites(
                desired = listOf(duplicate, duplicate.copy(text = "Two")),
                existing = emptyList(),
            )
        }.exceptionOrNull()

        assertThat(error).isInstanceOf(IllegalArgumentException::class.java)
    }

    private fun document(rowId: Long, key: String, text: String) = SearchDocumentEntity(
        rowId = rowId,
        documentKey = key,
        kind = SearchDocumentKind.CANONICAL_NAME,
        canonicalChannelId = "channel-a",
        text = text,
    )
}
